/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eval Pairs */
        get: operations["list_eval_pairs_api_evals_pairs_get"];
        put?: never;
        /** Create Eval Pair */
        post: operations["create_eval_pair_api_evals_pairs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/pairs/{eval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval Pair */
        get: operations["get_eval_pair_api_evals_pairs__eval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/pairs/{eval_id}/drain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drain Eval Pair */
        post: operations["drain_eval_pair_api_evals_pairs__eval_id__drain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eval Campaigns */
        get: operations["list_eval_campaigns_api_evals_campaigns_get"];
        put?: never;
        /** Create Eval Campaign */
        post: operations["create_eval_campaign_api_evals_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval Campaign */
        get: operations["get_eval_campaign_api_evals_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/campaigns/{campaign_id}/drain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drain Eval Campaign */
        post: operations["drain_eval_campaign_api_evals_campaigns__campaign_id__drain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/campaigns/{campaign_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Eval Campaign */
        post: operations["cancel_eval_campaign_api_evals_campaigns__campaign_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/drain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drain Run */
        post: operations["drain_run_api_runs__run_id__drain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Checkpoints */
        get: operations["list_checkpoints_api_runs__run_id__checkpoints_get"];
        put?: never;
        /** Create Checkpoint */
        post: operations["create_checkpoint_api_runs__run_id__checkpoints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkpoints/{checkpoint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint */
        get: operations["get_checkpoint_api_checkpoints__checkpoint_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkpoints/{checkpoint_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Checkpoint */
        post: operations["restore_checkpoint_api_checkpoints__checkpoint_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chaos/faults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arm Fault */
        post: operations["arm_fault_api_chaos_faults_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chaos/peer-probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Peer Probe */
        post: operations["peer_probe_api_chaos_peer_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projections/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Projections */
        post: operations["rebuild_projections_api_projections_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentView */
        AgentView: {
            /** Agent Id */
            agent_id: string;
            /** Role */
            role: string;
            /** Capabilities */
            capabilities?: string[];
            /** Status */
            status: string;
            /**
             * Max Concurrency
             * @default 1
             */
            max_concurrency: number;
            /** Last Heartbeat At */
            last_heartbeat_at?: string | null;
            /** Active Assignment Id */
            active_assignment_id?: string | null;
            /**
             * Mailbox Pending
             * @default 0
             */
            mailbox_pending: number;
            /**
             * In Flight
             * @default 0
             */
            in_flight: number;
            /** Active Run Id */
            active_run_id?: string | null;
            /** Last Error */
            last_error?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ApiErrorDetail */
        ApiErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            detail: components["schemas"]["ApiErrorDetail"];
        };
        /** AssignmentView */
        AssignmentView: {
            /** Assignment Id */
            assignment_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Agent Id */
            agent_id: string;
            /** Goal */
            goal: string;
            /** Exit Criteria */
            exit_criteria?: string[];
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** CampaignAggregate */
        CampaignAggregate: {
            /** Aggregator Version */
            aggregator_version: string;
            /** Sample Count */
            sample_count: number;
            /** Samples Sha256 */
            samples_sha256: string;
            /** Bootstrap Seed Sha256 */
            bootstrap_seed_sha256: string;
            /** Hard Reliability Regression */
            hard_reliability_regression: boolean;
            success_rate_delta: components["schemas"]["CampaignMetricEstimate"];
            quality_delta: components["schemas"]["CampaignMetricEstimate"];
            cost_ratio: components["schemas"]["CampaignMetricEstimate"];
            duration_ratio: components["schemas"]["CampaignMetricEstimate"];
        };
        /**
         * CampaignBudgetEnvelope
         * @description 父实验对全部 Single/Team Run 的静态最坏预算证明。
         */
        CampaignBudgetEnvelope: {
            /** Trial Count */
            trial_count: number;
            /** Per Arm Max Tokens */
            per_arm_max_tokens: number;
            /** Per Arm Max Cost Usd */
            per_arm_max_cost_usd: string;
            /** Max Total Tokens */
            max_total_tokens: number;
            /** Max Total Cost Usd */
            max_total_cost_usd: string;
        };
        /** CampaignMetricEstimate */
        CampaignMetricEstimate: {
            /**
             * Metric
             * @enum {string}
             */
            metric: "success_rate_delta" | "quality_delta" | "cost_ratio" | "duration_ratio";
            /** Point Ppm */
            point_ppm: number | null;
            /** Lower Bound Ppm */
            lower_bound_ppm: number | null;
            /** Upper Bound Ppm */
            upper_bound_ppm: number | null;
            /** Sample Size */
            sample_size: number;
            /**
             * Method
             * @enum {string}
             */
            method: "point_only" | "deterministic_paired_percentile";
            /** Resamples */
            resamples: number;
            /** Familywise Confidence Ppm */
            familywise_confidence_ppm: number;
            /**
             * Unbounded
             * @default false
             */
            unbounded: boolean;
        };
        /**
         * CampaignRecommendationPolicy
         * @description 所有数值都是初始治理门槛，必须由真实 Live Campaign 调优。
         */
        CampaignRecommendationPolicy: {
            /**
             * Version
             * @default campaign-policy-v1
             */
            version: string;
            /**
             * Minimum Interval Trials
             * @default 5
             */
            minimum_interval_trials: number;
            /**
             * Minimum Live Trials
             * @default 10
             */
            minimum_live_trials: number;
            /**
             * Minimum Success Delta Ppm
             * @default 0
             */
            minimum_success_delta_ppm: number;
            /**
             * Minimum Quality Delta Ppm
             * @default 10000
             */
            minimum_quality_delta_ppm: number;
            /**
             * Maximum Cost Ratio Ppm
             * @default 1500000
             */
            maximum_cost_ratio_ppm: number;
            /**
             * Maximum Duration Ratio Ppm
             * @default 1500000
             */
            maximum_duration_ratio_ppm: number;
            /**
             * Familywise Confidence Ppm
             * @default 950000
             */
            familywise_confidence_ppm: number;
            /**
             * Bootstrap Resamples
             * @default 10000
             */
            bootstrap_resamples: number;
        };
        /**
         * CampaignScope
         * @description 跨 Pair 聚合时必须保持不变的实验语义。
         */
        CampaignScope: {
            /** Task Pack */
            task_pack: string;
            /** Case Id */
            case_id: string;
            /** Fixture Hash */
            fixture_hash: string;
            /** Input Hash */
            input_hash: string;
            /** Scorer Version */
            scorer_version: string;
            evidence_tier: components["schemas"]["EvidenceTier"];
            /** Model Profile */
            model_profile: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Model Budget */
            model_budget: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Harness Profile */
            harness_profile: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** CampaignTrialPlan */
        CampaignTrialPlan: {
            /** Trial Index */
            trial_index: number;
            /** Pair Request Id */
            pair_request_id: string;
            /** Eval Id */
            eval_id: string;
        };
        /** CampaignTrialSummary */
        CampaignTrialSummary: {
            /** Trial Index */
            trial_index: number;
            /** Eval Id */
            eval_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "started" | "linked" | "released" | "observed" | "creation_failed";
            /** Evidence Valid */
            evidence_valid?: boolean | null;
            /**
             * Invalid Reasons
             * @default []
             */
            invalid_reasons: string[];
            sample?: components["schemas"]["PairedTrialSample"] | null;
        };
        /** CancelResult */
        CancelResult: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Active Cancelled */
            active_cancelled: number;
            /** Queued Cancelled */
            queued_cancelled: number;
        };
        /** CapabilityManifestView */
        CapabilityManifestView: {
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Turn Id */
            turn_id: string;
            /** Agent Id */
            agent_id: string;
            /** Assignment Id */
            assignment_id: string;
            /** Strategy */
            strategy: string;
            /**
             * Catalog Size
             * @default 0
             */
            catalog_size: number;
            /**
             * Disclosed Count
             * @default 0
             */
            disclosed_count: number;
            /**
             * Withheld Count
             * @default 0
             */
            withheld_count: number;
            /**
             * Excluded Count
             * @default 0
             */
            excluded_count: number;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** CheckpointContract */
        CheckpointContract: {
            /**
             * Schema Version
             * @default composite-checkpoint-v1
             * @constant
             */
            schema_version: "composite-checkpoint-v1";
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Request Id */
            request_id: string;
            /** Request Fingerprint */
            request_fingerprint: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Task Pack */
            task_pack: string;
            /** Baseline Identity */
            baseline_identity: string;
            source: components["schemas"]["CheckpointSourceBoundary"];
            workspace: components["schemas"]["WorkspaceSnapshot"];
            state_refs: components["schemas"]["CheckpointStateRefs"];
            effects: components["schemas"]["CheckpointEffectBoundary"];
            /**
             * Restore Policy
             * @default fork_only
             * @constant
             */
            restore_policy: "fork_only";
            /**
             * Context Policy
             * @default replan_from_verified_facts
             * @constant
             */
            context_policy: "replan_from_verified_facts";
            /**
             * Unknown Effect Policy
             * @default block
             * @constant
             */
            unknown_effect_policy: "block";
        };
        /** CheckpointCreateRequest */
        CheckpointCreateRequest: {
            /** Request Id */
            request_id: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** CheckpointEffect */
        CheckpointEffect: {
            /** Operation Id */
            operation_id: string;
            /** Tool Name */
            tool_name: string;
            /**
             * Terminal State
             * @enum {string}
             */
            terminal_state: "completed" | "failed" | "unknown";
            /** Side Effect Level */
            side_effect_level: string;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "read_only" | "workspace_restored" | "no_effect" | "requires_reconciliation" | "irreversible" | "unknown";
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** CheckpointEffectBoundary */
        CheckpointEffectBoundary: {
            /**
             * Effects
             * @default []
             */
            effects: components["schemas"]["CheckpointEffect"][];
            /**
             * Restore Blockers
             * @default []
             */
            restore_blockers: string[];
        };
        /** CheckpointRestoreRequest */
        CheckpointRestoreRequest: {
            /** Request Id */
            request_id: string;
        };
        /** CheckpointRestored */
        CheckpointRestored: {
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Source Run Id */
            source_run_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
        /** CheckpointSourceBoundary */
        CheckpointSourceBoundary: {
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Event Id */
            event_id: string;
            /** Event Cursor */
            event_cursor: number;
            /** Event Count */
            event_count: number;
            /** Event Prefix Sha256 */
            event_prefix_sha256: string;
            /** Turn Id */
            turn_id?: string | null;
            /** Phase */
            phase: string;
        };
        /** CheckpointStateRefs */
        CheckpointStateRefs: {
            /** Run Created Event Id */
            run_created_event_id: string;
            /** Assignment Event Id */
            assignment_event_id?: string | null;
            /** Local Plan Event Id */
            local_plan_event_id?: string | null;
            /** Context Manifest Event Id */
            context_manifest_event_id?: string | null;
            /**
             * Artifacts
             * @default []
             */
            artifacts: components["schemas"]["VerifiedArtifactRef"][];
        };
        /** ContextView */
        ContextView: {
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Agent Id */
            agent_id: string;
            /** Trigger Event Id */
            trigger_event_id: string;
            /** Context Epoch */
            context_epoch: number;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Microcompact */
            microcompact: {
                [key: string]: number;
            };
            /** Message Preview */
            message_preview?: {
                [key: string]: string;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** DrainResult */
        DrainResult: {
            /** Run Id */
            run_id: string;
            /** Steps */
            steps: number;
        };
        /** DreamJobView */
        DreamJobView: {
            /** Job Id */
            job_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
            /** Signal Id */
            signal_id?: string | null;
            /** Memory Candidate Id */
            memory_candidate_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * EvalCampaignContract
         * @description 任何子 Pair 执行前必须持久化的不可变实验计划。
         */
        EvalCampaignContract: {
            /**
             * Schema Version
             * @default eval-campaign-v1
             */
            schema_version: string;
            /**
             * Aggregator Version
             * @default paired-bootstrap-v1
             */
            aggregator_version: string;
            /** Campaign Id */
            campaign_id: string;
            /** Request Fingerprint */
            request_fingerprint: string;
            /** Title */
            title: string;
            /** Brief */
            brief: string;
            /** Task Pack */
            task_pack: string;
            /**
             * Model Mode
             * @enum {string}
             */
            model_mode: "scripted" | "deepseek";
            evidence_tier: components["schemas"]["EvidenceTier"];
            /** Planned Trial Count */
            planned_trial_count: number;
            /** Trials */
            trials: components["schemas"]["CampaignTrialPlan"][];
            /** Pair Model Budget */
            pair_model_budget: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            budget: components["schemas"]["CampaignBudgetEnvelope"];
            /**
             * Max Parallel Pairs
             * @default 1
             */
            max_parallel_pairs: number;
            policy?: components["schemas"]["CampaignRecommendationPolicy"];
        };
        /** EvalCampaignCreated */
        EvalCampaignCreated: {
            /** Campaign Id */
            campaign_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
            /** Planned Trial Count */
            planned_trial_count: number;
            budget: components["schemas"]["CampaignBudgetEnvelope"];
        };
        /** EvalCampaignReport */
        EvalCampaignReport: {
            /** Campaign Id */
            campaign_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "cancelled";
            contract: components["schemas"]["EvalCampaignContract"];
            scope?: components["schemas"]["CampaignScope"] | null;
            /** Scope Fingerprint */
            scope_fingerprint?: string | null;
            /** Planned Trial Count */
            planned_trial_count: number;
            /** Linked Trial Count */
            linked_trial_count: number;
            /** Released Trial Count */
            released_trial_count: number;
            /** Completed Trial Count */
            completed_trial_count: number;
            /** Invalid Trial Count */
            invalid_trial_count: number;
            /** Trials */
            trials: components["schemas"]["CampaignTrialSummary"][];
            /** Evidence Valid */
            evidence_valid: boolean;
            /**
             * Invalid Reasons
             * @default []
             */
            invalid_reasons: string[];
            aggregate?: components["schemas"]["CampaignAggregate"] | null;
            recommendation?: components["schemas"]["TeamRecommendationDecision"] | null;
        };
        /** EvalCampaignRequest */
        EvalCampaignRequest: {
            /** Request Id */
            request_id: string;
            /** Title */
            title: string;
            /** Brief */
            brief: string;
            /**
             * Model Mode
             * @default scripted
             * @enum {string}
             */
            model_mode: "scripted" | "deepseek";
            /**
             * Task Pack
             * @default repo-maintainer
             * @constant
             */
            task_pack: "repo-maintainer";
            /**
             * Trial Count
             * @default 3
             */
            trial_count: number;
            /**
             * Max Parallel Pairs
             * @default 1
             */
            max_parallel_pairs: number;
            model_budget?: components["schemas"]["ModelBudgetConfig"];
            /**
             * Campaign Max Total Tokens
             * @default 2500000
             */
            campaign_max_total_tokens: number;
            /**
             * Campaign Max Cost Usd
             * @default 1.00
             */
            campaign_max_cost_usd: number | string;
        };
        /**
         * Event
         * @description A durable event in a run trajectory.
         */
        Event: {
            /** Id */
            id?: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Type */
            type: string;
            /** Source */
            source: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Refs */
            refs?: string[];
            /** Causation Id */
            causation_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["EventRecord"][];
            /** Next Cursor */
            next_cursor: number;
        };
        /**
         * EventRecord
         * @description An Event plus its stable, monotonically increasing SSE cursor.
         */
        EventRecord: {
            /** Cursor */
            cursor: number;
            event: components["schemas"]["Event"];
        };
        /**
         * EvidenceTier
         * @enum {string}
         */
        EvidenceTier: "deterministic" | "live_paired";
        /** EvolutionView */
        EvolutionView: {
            /** Candidate Id */
            candidate_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Base Version */
            base_version?: string | null;
            /** Proposed Version */
            proposed_version?: string | null;
            /** Rationale */
            rationale?: string | null;
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Diffs */
            diffs?: {
                [key: string]: unknown;
            }[];
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Next Gate */
            next_gate?: string | null;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** FaultRequest */
        FaultRequest: {
            /** Point */
            point: string;
        };
        /** FaultResult */
        FaultResult: {
            /** Armed */
            armed: string;
            /** Mode */
            mode: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthView */
        HealthView: {
            /** Status */
            status: string;
            runtime: components["schemas"]["RuntimeView"];
            /** Version */
            version: string;
        };
        JsonValue: unknown;
        /** KernelDecision */
        KernelDecision: {
            /** Candidate Id */
            candidate_id: string;
            /** Accepted */
            accepted: boolean;
            /** Reason */
            reason: string;
            /** Event Ids */
            event_ids?: string[];
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /**
             * Recovered
             * @default false
             */
            recovered: boolean;
        };
        /** LeaseView */
        LeaseView: {
            /** Lease Id */
            lease_id: string;
            /** Assignment Id */
            assignment_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Agent Id */
            agent_id: string;
            /** Status */
            status: string;
            /** Stage Id */
            stage_id?: string | null;
            /** Acquired At */
            acquired_at: string;
            /** Expires At */
            expires_at: string;
            /** Renewed At */
            renewed_at?: string | null;
            /** Released At */
            released_at?: string | null;
            /** Expired At */
            expired_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** MemoryView */
        MemoryView: {
            /** Candidate Id */
            candidate_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Slot */
            slot?: string | null;
            /** Content */
            content?: string | null;
            /** Scope */
            scope?: string | null;
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Confidence */
            confidence?: number | null;
            /** Risk */
            risk?: string | null;
            /** Admission Zone */
            admission_zone?: string | null;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** ModelBudgetConfig */
        ModelBudgetConfig: {
            /**
             * Max Total Tokens
             * @default 250000
             */
            max_total_tokens: number;
            /**
             * Max Cost Usd
             * @default 0.10
             */
            max_cost_usd: number | string;
            /**
             * Max Concurrent Calls
             * @default 2
             */
            max_concurrent_calls: number;
            /**
             * Max Output Tokens Per Call
             * @default 4096
             */
            max_output_tokens_per_call: number;
            /**
             * Max Retries Per Call
             * @default 2
             */
            max_retries_per_call: number;
        };
        /** ModelBudgetView */
        ModelBudgetView: {
            /** Run Id */
            run_id: string;
            /** Active Calls */
            active_calls: number;
            /** Completed Calls */
            completed_calls: number;
            /** Unknown Calls */
            unknown_calls: number;
            /** Spent Tokens */
            spent_tokens: number;
            /** Committed Tokens */
            committed_tokens: number;
            /** Remaining Tokens */
            remaining_tokens: number;
            /** Estimated Spent Microusd */
            estimated_spent_microusd: number;
            /** Committed Cost Microusd */
            committed_cost_microusd: number;
            /** Remaining Cost Microusd */
            remaining_cost_microusd: number;
            /** Cost Kind */
            cost_kind: string;
        } & {
            [key: string]: unknown;
        };
        /** ModelCallView */
        ModelCallView: {
            /** Call Id */
            call_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Agent Id */
            agent_id: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** State */
            state: string;
            /** Attempt Count */
            attempt_count: number;
            /** Reserved Input Tokens */
            reserved_input_tokens: number;
            /** Reserved Output Tokens */
            reserved_output_tokens: number;
            /** Reserved Cost Microusd */
            reserved_cost_microusd: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * PairedEvalArm
         * @description Immutable identity and resource envelope for one side of an eval pair.
         */
        PairedEvalArm: {
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "single" | "team";
            /** Run Id */
            run_id: string;
            /**
             * Workspace
             * Format: path
             */
            workspace: string;
            /** Input Hash */
            input_hash: string;
            /** Model Profile */
            model_profile: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Model Budget */
            model_budget: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** PairedEvalArmReport */
        PairedEvalArmReport: {
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "single" | "team";
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            score?: components["schemas"]["RepoMaintainerScore"] | null;
            trace?: components["schemas"]["RunTraceMetrics"] | null;
        };
        /**
         * PairedEvalContract
         * @description Fail-closed proof that Single and Team are mechanically comparable.
         */
        PairedEvalContract: {
            /** Eval Id */
            eval_id: string;
            /** Case Id */
            case_id: string;
            /** Task Pack */
            task_pack: string;
            /** Fixture Hash */
            fixture_hash: string;
            /** Scorer Version */
            scorer_version: string;
            evidence_tier: components["schemas"]["EvidenceTier"];
            /** Harness Profile */
            harness_profile?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            single: components["schemas"]["PairedEvalArm"];
            team: components["schemas"]["PairedEvalArm"];
        };
        /**
         * PairedEvalCreateRequest
         * @description 公开 Pair DTO；父子 Link 与释放策略只由 Harness 内部持有。
         */
        PairedEvalCreateRequest: {
            /** Request Id */
            request_id: string;
            /** Title */
            title: string;
            /** Brief */
            brief: string;
            /**
             * Model Mode
             * @default scripted
             * @enum {string}
             */
            model_mode: "scripted" | "deepseek";
            /**
             * Task Pack
             * @default repo-maintainer
             * @constant
             */
            task_pack: "repo-maintainer";
            model_budget?: components["schemas"]["ModelBudgetConfig"];
        };
        /** PairedEvalCreated */
        PairedEvalCreated: {
            /** Eval Id */
            eval_id: string;
            /** Single Run Id */
            single_run_id: string;
            /** Team Run Id */
            team_run_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
        /** PairedEvalReport */
        PairedEvalReport: {
            /** Eval Id */
            eval_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed";
            contract: components["schemas"]["PairedEvalContract"];
            single: components["schemas"]["PairedEvalArmReport"];
            team: components["schemas"]["PairedEvalArmReport"];
            /**
             * Evidence Valid
             * @default true
             */
            evidence_valid: boolean;
            /**
             * Invalid Reasons
             * @default []
             */
            invalid_reasons: string[];
            recommendation?: components["schemas"]["TeamRecommendationDecision"] | null;
        };
        /**
         * PairedTrialSample
         * @description 一个 Pair 的不可拆分统计样本，只接受已验证的机器事实。
         */
        PairedTrialSample: {
            /** Trial Index */
            trial_index: number;
            /** Eval Id */
            eval_id: string;
            /** Pair Report Sha256 */
            pair_report_sha256: string;
            /** Single Run Id */
            single_run_id: string;
            /** Team Run Id */
            team_run_id: string;
            /** Single Terminal Event Id */
            single_terminal_event_id: string;
            /** Team Terminal Event Id */
            team_terminal_event_id: string;
            /** Single Success */
            single_success: boolean;
            /** Team Success */
            team_success: boolean;
            /** Single Quality Ppm */
            single_quality_ppm: number;
            /** Team Quality Ppm */
            team_quality_ppm: number;
            /** Single Committed Cost Microusd */
            single_committed_cost_microusd: number;
            /** Team Committed Cost Microusd */
            team_committed_cost_microusd: number;
            /** Single Duration Ms */
            single_duration_ms: number;
            /** Team Duration Ms */
            team_duration_ms: number;
            /**
             * Hard Reliability Regression
             * @default false
             */
            hard_reliability_regression: boolean;
        };
        /** PeerProbeRequest */
        PeerProbeRequest: {
            /** Run Id */
            run_id: string;
            /** Sender */
            sender: string;
            /** Receiver */
            receiver: string;
            /** Depth */
            depth: number;
        };
        /** QueuedDeliveryView */
        QueuedDeliveryView: {
            /** Delivery Id */
            delivery_id: string;
            /** Worker Id */
            worker_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Event Type */
            event_type: string;
            /** Assignment Id */
            assignment_id?: string | null;
            /** Stage Id */
            stage_id?: string | null;
            /** Position */
            position: number;
            /** Claim State */
            claim_state?: string | null;
            /** Fencing Token */
            fencing_token?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** RebuildResult */
        RebuildResult: {
            /** Status */
            status: string;
        };
        /**
         * RecommendationOutcome
         * @enum {string}
         */
        RecommendationOutcome: "insufficient_live_evidence" | "recommend_team" | "keep_single";
        /** RepoMaintainerScore */
        RepoMaintainerScore: {
            /**
             * Scorer Version
             * @default repo-maintainer-v2
             */
            scorer_version: string;
            /** Passed */
            passed: boolean;
            /** Score */
            score: number;
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
            /** Changed Files */
            changed_files: string[];
            /**
             * Test Output
             * @default
             */
            test_output: string;
        };
        /** RunCreated */
        RunCreated: {
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /**
         * RunTraceMetrics
         * @description Replay-stable metrics derived only from durable events and budget facts.
         */
        RunTraceMetrics: {
            /** Run Id */
            run_id: string;
            /**
             * Terminal Status
             * @enum {string}
             */
            terminal_status: "succeeded" | "failed" | "cancelled";
            /** Terminal Event Id */
            terminal_event_id: string;
            /** Duration Ms */
            duration_ms: number;
            /** Model Requests */
            model_requests: number;
            /** Model Completions */
            model_completions: number;
            /** Physical Model Attempts */
            physical_model_attempts: number;
            /** Tool Requests */
            tool_requests: number;
            /** Tool Completions */
            tool_completions: number;
            /** Operations Started */
            operations_started: number;
            /** Operations Completed */
            operations_completed: number;
            /** A2A Requests */
            a2a_requests: number;
            /** A2A Responses */
            a2a_responses: number;
            /** Assignment Failures */
            assignment_failures: number;
            /** Assignment Retries */
            assignment_retries: number;
            /** Operation Unknowns */
            operation_unknowns: number;
            /** Model Unknown Calls */
            model_unknown_calls: number;
            /** Dead Letters */
            dead_letters: number;
            /** Spent Tokens */
            spent_tokens: number;
            /** Committed Tokens */
            committed_tokens: number;
            /** Spent Cost Microusd */
            spent_cost_microusd: number;
            /** Committed Cost Microusd */
            committed_cost_microusd: number;
        };
        /** RunView */
        RunView: {
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /**
             * Brief
             * @default
             */
            brief: string;
            /** Status */
            status: string;
            /** Phase */
            phase: string;
            /** Model Mode */
            model_mode: string;
            /** Behavior Version */
            behavior_version: string;
            /**
             * Event Count
             * @default 0
             */
            event_count: number;
            /**
             * Last Cursor
             * @default 0
             */
            last_cursor: number;
            /** Completion Gate */
            completion_gate?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RuntimeView */
        RuntimeView: {
            /** Status */
            status: string;
            /** Latest Event Id */
            latest_event_id?: string | null;
            /** Deepseek Configured */
            deepseek_configured: boolean;
            /** Fact Source */
            fact_source: string;
            /** Generated At */
            generated_at: string;
            /** Scheduler */
            scheduler: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** SnapshotView */
        SnapshotView: {
            run: components["schemas"]["RunView"] | null;
            /** Agents */
            agents: components["schemas"]["AgentView"][];
            /** Assignments */
            assignments: components["schemas"]["AssignmentView"][];
            /** Leases */
            leases: components["schemas"]["LeaseView"][];
            /** Contexts */
            contexts: components["schemas"]["ContextView"][];
            /** Capability Manifests */
            capability_manifests: components["schemas"]["CapabilityManifestView"][];
            /** Memories */
            memories: components["schemas"]["MemoryView"][];
            /** Evolutions */
            evolutions: components["schemas"]["EvolutionView"][];
            /** Dream Jobs */
            dream_jobs: components["schemas"]["DreamJobView"][];
            /** Queued Deliveries */
            queued_deliveries: components["schemas"]["QueuedDeliveryView"][];
            /** Work Claims */
            work_claims: components["schemas"]["WorkClaimView"][];
            model_budget: components["schemas"]["ModelBudgetView"] | null;
            /** Model Calls */
            model_calls: components["schemas"]["ModelCallView"][];
            runtime: components["schemas"]["RuntimeView"];
        };
        /** TaskRequest */
        TaskRequest: {
            /** Title */
            title: string;
            /** Brief */
            brief: string;
            /**
             * Model Mode
             * @default scripted
             * @enum {string}
             */
            model_mode: "scripted" | "deepseek";
            /**
             * Execution Mode
             * @default team
             * @enum {string}
             */
            execution_mode: "team" | "single";
            /** Task Pack */
            task_pack?: ("resident-demo" | "repo-maintainer" | "evidence-research") | null;
            model_budget?: components["schemas"]["ModelBudgetConfig"];
        };
        /** TeamRecommendationDecision */
        TeamRecommendationDecision: {
            outcome: components["schemas"]["RecommendationOutcome"];
            /** Reason */
            reason: string;
            /**
             * Failed Thresholds
             * @default []
             */
            failed_thresholds: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifiedArtifactRef */
        VerifiedArtifactRef: {
            /** Artifact Id */
            artifact_id: string;
            /** Kind */
            kind: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Source Event Id */
            source_event_id: string;
            /** Size */
            size: number;
            /** Sha256 */
            sha256: string;
        };
        /** WorkClaimView */
        WorkClaimView: {
            /** Claim Key */
            claim_key: string;
            /** Owner Id */
            owner_id: string;
            /** Fencing Token */
            fencing_token: number;
            /** State */
            state: string;
            /** Claimed At */
            claimed_at: string;
            /** Expires At */
            expires_at: string;
            /** Updated At */
            updated_at: string;
        } & {
            [key: string]: unknown;
        };
        /** WorkspaceFileEntry */
        WorkspaceFileEntry: {
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Sha256 */
            sha256: string;
        };
        /** WorkspaceSnapshot */
        WorkspaceSnapshot: {
            /**
             * Schema Version
             * @default workspace-snapshot-v1
             * @constant
             */
            schema_version: "workspace-snapshot-v1";
            /** Object Id */
            object_id: string;
            /** Archive Sha256 */
            archive_sha256: string;
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** File Count */
            file_count: number;
            /** Total Bytes */
            total_bytes: number;
            /**
             * Files
             * @default []
             */
            files: components["schemas"]["WorkspaceFileEntry"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_pairs_api_evals_pairs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairedEvalReport"][];
                };
            };
        };
    };
    create_eval_pair_api_evals_pairs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairedEvalCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairedEvalCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_pair_api_evals_pairs__eval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairedEvalReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drain_eval_pair_api_evals_pairs__eval_id__drain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairedEvalReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_campaigns_api_evals_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCampaignReport"][];
                };
            };
        };
    };
    create_eval_campaign_api_evals_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalCampaignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCampaignCreated"];
                };
            };
            /** @description Invalid campaign */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Campaign conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_campaign_api_evals_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCampaignReport"];
                };
            };
            /** @description Campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drain_eval_campaign_api_evals_campaigns__campaign_id__drain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCampaignReport"];
                };
            };
            /** @description Campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_eval_campaign_api_evals_campaigns__campaign_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCampaignReport"];
                };
            };
            /** @description Campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Cancellation conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drain_run_api_runs__run_id__drain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrainResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_checkpoints_api_runs__run_id__checkpoints_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointContract"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkpoint_api_runs__run_id__checkpoints_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckpointCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointContract"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoint_api_checkpoints__checkpoint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkpoint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointContract"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_checkpoint_api_checkpoints__checkpoint_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkpoint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckpointRestoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointRestored"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_snapshot_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                after?: number;
                run_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_events_stream_get: {
        parameters: {
            query?: {
                after?: number;
                run_id?: string | null;
                once?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arm_fault_api_chaos_faults_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    peer_probe_api_chaos_peer_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerProbeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KernelDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_projections_api_projections_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RebuildResult"];
                };
            };
        };
    };
}
