/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/drain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drain Run */
        post: operations["drain_run_api_runs__run_id__drain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chaos/faults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arm Fault */
        post: operations["arm_fault_api_chaos_faults_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chaos/peer-probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Peer Probe */
        post: operations["peer_probe_api_chaos_peer_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projections/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Projections */
        post: operations["rebuild_projections_api_projections_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentView */
        AgentView: {
            /** Agent Id */
            agent_id: string;
            /** Role */
            role: string;
            /** Capabilities */
            capabilities?: string[];
            /** Status */
            status: string;
            /**
             * Max Concurrency
             * @default 1
             */
            max_concurrency: number;
            /** Last Heartbeat At */
            last_heartbeat_at?: string | null;
            /** Active Assignment Id */
            active_assignment_id?: string | null;
            /**
             * Mailbox Pending
             * @default 0
             */
            mailbox_pending: number;
            /**
             * In Flight
             * @default 0
             */
            in_flight: number;
            /** Active Run Id */
            active_run_id?: string | null;
            /** Last Error */
            last_error?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** AssignmentView */
        AssignmentView: {
            /** Assignment Id */
            assignment_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Agent Id */
            agent_id: string;
            /** Goal */
            goal: string;
            /** Exit Criteria */
            exit_criteria?: string[];
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** CancelResult */
        CancelResult: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Active Cancelled */
            active_cancelled: number;
            /** Queued Cancelled */
            queued_cancelled: number;
        };
        /** CapabilityManifestView */
        CapabilityManifestView: {
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Turn Id */
            turn_id: string;
            /** Agent Id */
            agent_id: string;
            /** Assignment Id */
            assignment_id: string;
            /** Strategy */
            strategy: string;
            /**
             * Catalog Size
             * @default 0
             */
            catalog_size: number;
            /**
             * Disclosed Count
             * @default 0
             */
            disclosed_count: number;
            /**
             * Withheld Count
             * @default 0
             */
            withheld_count: number;
            /**
             * Excluded Count
             * @default 0
             */
            excluded_count: number;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** ContextView */
        ContextView: {
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Agent Id */
            agent_id: string;
            /** Trigger Event Id */
            trigger_event_id: string;
            /** Context Epoch */
            context_epoch: number;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Microcompact */
            microcompact: {
                [key: string]: number;
            };
            /** Message Preview */
            message_preview?: {
                [key: string]: string;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** DrainResult */
        DrainResult: {
            /** Run Id */
            run_id: string;
            /** Steps */
            steps: number;
        };
        /** DreamJobView */
        DreamJobView: {
            /** Job Id */
            job_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
            /** Signal Id */
            signal_id?: string | null;
            /** Memory Candidate Id */
            memory_candidate_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Event
         * @description A durable event in a run trajectory.
         */
        Event: {
            /** Id */
            id?: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Type */
            type: string;
            /** Source */
            source: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Refs */
            refs?: string[];
            /** Causation Id */
            causation_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["EventRecord"][];
            /** Next Cursor */
            next_cursor: number;
        };
        /**
         * EventRecord
         * @description An Event plus its stable, monotonically increasing SSE cursor.
         */
        EventRecord: {
            /** Cursor */
            cursor: number;
            event: components["schemas"]["Event"];
        };
        /** EvolutionView */
        EvolutionView: {
            /** Candidate Id */
            candidate_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Base Version */
            base_version?: string | null;
            /** Proposed Version */
            proposed_version?: string | null;
            /** Rationale */
            rationale?: string | null;
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Diffs */
            diffs?: {
                [key: string]: unknown;
            }[];
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Next Gate */
            next_gate?: string | null;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** FaultRequest */
        FaultRequest: {
            /** Point */
            point: string;
        };
        /** FaultResult */
        FaultResult: {
            /** Armed */
            armed: string;
            /** Mode */
            mode: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthView */
        HealthView: {
            /** Status */
            status: string;
            runtime: components["schemas"]["RuntimeView"];
            /** Version */
            version: string;
        };
        /** KernelDecision */
        KernelDecision: {
            /** Candidate Id */
            candidate_id: string;
            /** Accepted */
            accepted: boolean;
            /** Reason */
            reason: string;
            /** Event Ids */
            event_ids?: string[];
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /**
             * Recovered
             * @default false
             */
            recovered: boolean;
        };
        /** LeaseView */
        LeaseView: {
            /** Lease Id */
            lease_id: string;
            /** Assignment Id */
            assignment_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Agent Id */
            agent_id: string;
            /** Status */
            status: string;
            /** Stage Id */
            stage_id?: string | null;
            /** Acquired At */
            acquired_at: string;
            /** Expires At */
            expires_at: string;
            /** Renewed At */
            renewed_at?: string | null;
            /** Released At */
            released_at?: string | null;
            /** Expired At */
            expired_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** MemoryView */
        MemoryView: {
            /** Candidate Id */
            candidate_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Slot */
            slot?: string | null;
            /** Content */
            content?: string | null;
            /** Scope */
            scope?: string | null;
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Confidence */
            confidence?: number | null;
            /** Risk */
            risk?: string | null;
            /** Admission Zone */
            admission_zone?: string | null;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** ModelBudgetConfig */
        ModelBudgetConfig: {
            /**
             * Max Total Tokens
             * @default 250000
             */
            max_total_tokens: number;
            /**
             * Max Cost Usd
             * @default 0.10
             */
            max_cost_usd: number | string;
            /**
             * Max Concurrent Calls
             * @default 2
             */
            max_concurrent_calls: number;
            /**
             * Max Output Tokens Per Call
             * @default 4096
             */
            max_output_tokens_per_call: number;
            /**
             * Max Retries Per Call
             * @default 2
             */
            max_retries_per_call: number;
        };
        /** ModelBudgetView */
        ModelBudgetView: {
            /** Run Id */
            run_id: string;
            /** Active Calls */
            active_calls: number;
            /** Completed Calls */
            completed_calls: number;
            /** Unknown Calls */
            unknown_calls: number;
            /** Spent Tokens */
            spent_tokens: number;
            /** Committed Tokens */
            committed_tokens: number;
            /** Remaining Tokens */
            remaining_tokens: number;
            /** Estimated Spent Microusd */
            estimated_spent_microusd: number;
            /** Committed Cost Microusd */
            committed_cost_microusd: number;
            /** Remaining Cost Microusd */
            remaining_cost_microusd: number;
            /** Cost Kind */
            cost_kind: string;
        } & {
            [key: string]: unknown;
        };
        /** ModelCallView */
        ModelCallView: {
            /** Call Id */
            call_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Agent Id */
            agent_id: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** State */
            state: string;
            /** Attempt Count */
            attempt_count: number;
            /** Reserved Input Tokens */
            reserved_input_tokens: number;
            /** Reserved Output Tokens */
            reserved_output_tokens: number;
            /** Reserved Cost Microusd */
            reserved_cost_microusd: number;
        } & {
            [key: string]: unknown;
        };
        /** PeerProbeRequest */
        PeerProbeRequest: {
            /** Run Id */
            run_id: string;
            /** Sender */
            sender: string;
            /** Receiver */
            receiver: string;
            /** Depth */
            depth: number;
        };
        /** QueuedDeliveryView */
        QueuedDeliveryView: {
            /** Delivery Id */
            delivery_id: string;
            /** Worker Id */
            worker_id: string;
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Event Type */
            event_type: string;
            /** Assignment Id */
            assignment_id?: string | null;
            /** Stage Id */
            stage_id?: string | null;
            /** Position */
            position: number;
            /** Claim State */
            claim_state?: string | null;
            /** Fencing Token */
            fencing_token?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** RebuildResult */
        RebuildResult: {
            /** Status */
            status: string;
        };
        /** RunCreated */
        RunCreated: {
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /** RunView */
        RunView: {
            /** Run Id */
            run_id: string;
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /**
             * Brief
             * @default
             */
            brief: string;
            /** Status */
            status: string;
            /** Phase */
            phase: string;
            /** Model Mode */
            model_mode: string;
            /** Behavior Version */
            behavior_version: string;
            /**
             * Event Count
             * @default 0
             */
            event_count: number;
            /**
             * Last Cursor
             * @default 0
             */
            last_cursor: number;
            /** Completion Gate */
            completion_gate?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RuntimeView */
        RuntimeView: {
            /** Status */
            status: string;
            /** Latest Event Id */
            latest_event_id?: string | null;
            /** Deepseek Configured */
            deepseek_configured: boolean;
            /** Fact Source */
            fact_source: string;
            /** Generated At */
            generated_at: string;
            /** Scheduler */
            scheduler: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** SnapshotView */
        SnapshotView: {
            run: components["schemas"]["RunView"] | null;
            /** Agents */
            agents: components["schemas"]["AgentView"][];
            /** Assignments */
            assignments: components["schemas"]["AssignmentView"][];
            /** Leases */
            leases: components["schemas"]["LeaseView"][];
            /** Contexts */
            contexts: components["schemas"]["ContextView"][];
            /** Capability Manifests */
            capability_manifests: components["schemas"]["CapabilityManifestView"][];
            /** Memories */
            memories: components["schemas"]["MemoryView"][];
            /** Evolutions */
            evolutions: components["schemas"]["EvolutionView"][];
            /** Dream Jobs */
            dream_jobs: components["schemas"]["DreamJobView"][];
            /** Queued Deliveries */
            queued_deliveries: components["schemas"]["QueuedDeliveryView"][];
            /** Work Claims */
            work_claims: components["schemas"]["WorkClaimView"][];
            model_budget: components["schemas"]["ModelBudgetView"] | null;
            /** Model Calls */
            model_calls: components["schemas"]["ModelCallView"][];
            runtime: components["schemas"]["RuntimeView"];
        };
        /** TaskRequest */
        TaskRequest: {
            /** Title */
            title: string;
            /** Brief */
            brief: string;
            /**
             * Model Mode
             * @default scripted
             * @enum {string}
             */
            model_mode: "scripted" | "deepseek";
            /**
             * Execution Mode
             * @default team
             * @enum {string}
             */
            execution_mode: "team" | "single";
            /** Task Pack */
            task_pack?: ("resident-demo" | "repo-maintainer" | "evidence-research") | null;
            model_budget?: components["schemas"]["ModelBudgetConfig"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkClaimView */
        WorkClaimView: {
            /** Claim Key */
            claim_key: string;
            /** Owner Id */
            owner_id: string;
            /** Fencing Token */
            fencing_token: number;
            /** State */
            state: string;
            /** Claimed At */
            claimed_at: string;
            /** Expires At */
            expires_at: string;
            /** Updated At */
            updated_at: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drain_run_api_runs__run_id__drain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrainResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_snapshot_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                after?: number;
                run_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_events_stream_get: {
        parameters: {
            query?: {
                after?: number;
                run_id?: string | null;
                once?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arm_fault_api_chaos_faults_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    peer_probe_api_chaos_peer_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeerProbeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KernelDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_projections_api_projections_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RebuildResult"];
                };
            };
        };
    };
}
